server:
    port: 8091
    #servlet.context-path: /zkhyWeb
    context-path: /zkhyWeb
    session-timeout: 30
    tomcat.max-threads: 0
    tomcat.uri-encoding: UTF-8

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/zkhy_website1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: admin
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
    #热部署
    devtools.restart:
        enabled: true
        exclude: WEB-INF/**
    
    #统一日期处理
    jackson:
      default-property-inclusion: NON_NULL
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      #serialization:
      #     write-dates-as-timestamps: true
      
    #上传限制  
    http:
        multipart:
            maxFileSize: 100Mb
            maxRequestSize: 1000Mb
      
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath*:mybatis/*Mapper.xml
    type-aliases-package: com.zkhy.officialWebsite.model  # 注意：对应实体类的路径
    configuration:
        map-underscore-to-camel-case: true
    show-sql: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

log:
    level: debug
    path: ./logs/test/
    name: zkhyWeb
